### PR TITLE
MKII Weapons added

### PR DESCRIPTION
**Pull request by P4R4NORM4L**
Added MKII Weapons to the weapons.lua file

### CODE REVIEW

**Review by MrGriefs — CHANGES_REQUESTED** [review]
Hexadecimal must start with `0x`.

**Comment by P4R4NORM4L** [comment]
Does it matter if it's 0X or 0x?

**Comment by MrGriefs** [comment]
This repo follows a strict Lua style.

**Comment by P4R4NORM4L** [comment]
> This repo follows a strict Lua style.

Oh ok the changes have been made:)

**Pull request merged**
